### ISSUE TITLE
[BUG] Startup "I'm Back!" announcement readjustment

### ISSUE THREAD

**Issue by Barbercrew3809** [maxplayle04/MaxBot#24]
says back online after restart

**Comment by thatmaxplayle** [comment]
Hopefully fixed; will monitor for problems, especially with the bug-tracker. Please mention this issue in any further issues regarding this problem. Just type #24 to do so.

This problem should have been fixed, as the "👋Hey, I'm back!" will now not fire as it is prevented from being executed when a Reconnect event has fired. 

**Please mention this issue in any further issues you encounter on this subject, by typing #24. Thank you for reporting this issue.**
