### ISSUE TITLE
Review cross-server compatibility for AnnounceStartupInGeneral 

### ISSUE THREAD

**Issue by thatmaxplayle** [maxplayle04/MaxBot#7]
Should be able to use into a lot of the code from the Update Service for per-server functionality, however, need to check that announceStartupInGeneral is cross-server.

**Comment by VortexChelmsford** [comment]
This isn't cross-server compatible. Needs looking into, @maxplayle04

**Comment by thatmaxplayle** [comment]
Done! 1.0.8
